### PR TITLE
Feature 80/basicauth testspassing

### PR DESCRIPTION
**Pull request by Maroju100**
Added basic auth for passing tests when micronaut security is enabled

### CODE REVIEW

**Comment by mkimberlin** [comment]
@Bagurp will this play nicely with your oauth PR?

@Maroju100 how do we ensure that the AuthenticationProvider you added here is only applied for tests?

**Comment by Bagurp** [comment]
> 
> 
> @Bagurp will this play nicely with your oauth PR?
> 
> @Maroju100 how do we ensure that the AuthenticationProvider you added here is only applied for tests?

@mkimberlin Yes, we will have some merge conflicts but it should be good otherwise. Upon merging this PR, all our unit tests should start running.

**Comment by Maroju100** [comment]
> @Bagurp will this play nicely with your oauth PR?
> 
> @Maroju100 how do we ensure that the AuthenticationProvider you added here is only applied for tests?

**Comment by Maroju100** [comment]
Accidentally closed the pull request, reopening again

**Comment by Maroju100** [comment]
> @Bagurp will this play nicely with your oauth PR?
> 
> @Maroju100 how do we ensure that the AuthenticationProvider you added here is only applied for tests?

@mkimberlin Right now AuthenticationProvider is added to the application, this is how tutorials describe, checking ways to apply only to tests if possible. Let me know if anybody have some idea.

**Comment by mkimberlin** [comment]
@Maroju100 Curious where this stands (sorry, I should have been at standup to ask).  Branch needs an update, obviously...but also curious if you were able to get the required environment stuff working?

**Pull request closed without merging**
